#### Options ####

# GBA rom header
TITLE       := MARIOPARTYUS
GAME_CODE   := B8ME
MAKER_CODE  := 01
REVISION    := 0

# Don't echo build commands unless VERBOSE is set
VERBOSE ?= 0
ifeq ($(VERBOSE),0)
  QUIET := @
endif

#### Tools ####

CC1      := tools/agbcc/bin/agbcc
CC1_OLD  := tools/agbcc/bin/old_agbcc
CPP      := $(DEVKITARM)/bin/arm-none-eabi-cpp
AS       := $(DEVKITARM)/bin/arm-none-eabi-as
LD       := $(DEVKITARM)/bin/arm-none-eabi-ld
OBJCOPY  := $(DEVKITARM)/bin/arm-none-eabi-objcopy


####  todo: add other tools when needed ####
GBAFIX   := tools/gbafix/gbafix


CC1FLAGS := -mthumb-interwork -Wimplicit -Wparentheses -Werror -O2 -fhex-asm -fno-common
CPPFLAGS := -I tools/agbcc/include -iquote include -nostdinc -undef
ASFLAGS  := -mcpu=arm7tdmi -mthumb-interwork -I asminclude
LIBS := tools/agbcc/lib/libgcc.a tools/agbcc/lib/libc.a


#### Files ####

ROM      := MPAdvance.gba
ELF      := $(ROM:.gba=.elf)
MAP      := $(ROM:.gba=.map)
LDSCRIPT := ldscript.txt
CFILES   := $(wildcard src/*.c) $(wildcard src/*/*.c) $(wildcard src/*/*/*.c) $(wildcard src/*/*/*/*.c)
SFILES   := $(wildcard asm/*.s) $(wildcard asm/*/*.s) $(wildcard asm/*/*/*.s) $(wildcard asm/*/*/*/*.s) $(wildcard data/*.s)
OFILES   := $(SFILES:.s=.o) $(CFILES:.c=.o)
DEP_FILES := $(CFILES:.c=.dep)

src/eeprom.o: CC1FLAGS := -mthumb-interwork -Wimplicit -Wparentheses -Werror -O1 -fhex-asm -g


#### Main Targets ####

compare: $(ROM)
	$(QUIET) md5sum -c checksum.md5

clean:
	$(RM) $(ROM) $(ELF) $(MAP) $(OFILES) $(DEP_FILES) ldscript.txt src/*.s src/*/*.s src/*/*/*.s src/*/*/*/*.s

# Compile a set of baserom objects for use with objdiff
baserom-objs: compare
	mkdir -p baserom-objs && rm -f baserom-objs/*
	cp src/*.o baserom-objs
	cp asm/*.o baserom-objs

#### Recipes ####

$(ELF): $(OFILES) $(LDSCRIPT)
	@echo 'Linking $@'
	$(QUIET) $(LD) -T $(LDSCRIPT) -Map $(MAP) $(LIBS) -o $@
	$(QUIET) $(GBAFIX) $@ -t"$(TITLE)" -c$(GAME_CODE) -m$(MAKER_CODE) -r$(REVISION) --silent

%.gba: %.elf
	@echo 'Generating ROM $@'
	$(QUIET) $(OBJCOPY) -O binary --pad-to 0x08800000 --gap-fill 0xFF $< $@

%.o: %.c
	@echo 'Compiling $<'
	$(QUIET) $(CPP) $(CPPFLAGS) -MMD -MF $(@:.o=.dep) -MT $@ $< | $(CC1) $(CC1FLAGS) -o $*.s
	@printf "\t.text\n\t.align\t2, 0 @ Don't pad with nop\n" >> $*.s
	$(QUIET) $(AS) $(ASFLAGS) $*.s -o $*.o

%.o: %.s
	@echo 'Assembling $<'
	$(QUIET) $(AS) $(ASFLAGS) $< -o $@

ldscript.txt: ldscript.in
	@echo '/* Autogenerated - do not edit. Edit $< instead. */' > $@
	$(CPP) -P $< >> $@


# Automatic dependency generation
-include $(DEP_FILES)
